version: '3.2'
services:
    mariadb:
      image: mariadb:10.9.4
      command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      hostname: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
          - ./mariadb:/var/lib/mysql
      tty: true
      ports:
          - 3306:3306